#!/usr/bin/env bash
# creating a nginx server

sudo apt-get update -y
sudo apt-get -y install nginx

# Overwrite the index file with 'Hello World!'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

sudo service nginx start
