#!/usr/bin/env bash
# creating a nginx server

sudo apt-get update -y
sudo apt-get -y install nginx

# Overwrite the index file with 'Hello World!'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
