#!/usr/bin/env bash
# creating a nginx server

sudo apt-get update -y
sudo apt-get -y install nginx

# Overwrite the index file with 'Hello World!'
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee  /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
