#!/usr/bin/env bash
# adding a custom header

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
sudo touch /var/www/html/404.html
sudo sh -c "echo 'Ceci n'est pas une page' > /var/www/html/404.html"

sudo sh -c 'printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By '"$(hostname)"';
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=xJJsoquu70o/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-enabled/default'

sudo service nginx restart
