#!/usr/bin/env bash
# setting up nginx as a load balancer


sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update -y
sudo apt-get install -y haproxy=2.4.\*
	

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 246968-web-01 52.91.136.4
	server 246968-web-01 34.229.184.55" >> /etc/haproxy/haproxy.cfg
	

sudo service haproxy restart
