#!/usr/bin/env bash
# setting up nginx as a load balancer

sudo apt-get install nginx
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get install -y haproxy=2.8.\*
sudo apt-get install nginx

load_balancer="\nfrontend http\n
\tbind *:80
\tmode http
\tdefault_backend load_b

backend load_b\n
\tbalance roundrobin
\tserver 246968-web-01 52.91.136.4:80 check
\tserver 246968-web-02 34.229.184.55:80 check
"
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
