#!/usr/bin/env bash
# checking if file exists
f="school"
if [ -a "$f" ]
then
	echo "school file exists"
	if [ -s "$f" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$f" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
